version: "3.3"
services:
  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: banlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Somkid058848391
    ports:
      - 5432:5432
    volumes:
     - ./private/var/lib/postgresql:/var/lib/postgresql
    restart: always
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: pgadmin4
    ports:
      - 7778:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    hostname: pgadmin4
    restart: always
    networks:
      - db-network

networks:
  db-network:
    external:
      name: my-mongo-cluster