version: "3.3"
services:
  backendnginx:
    restart: always
    # image: backendnginx
    build: .
    # container_name: backendnginx
    ports:
      - 8055:80
    volumes:
      - "./modules:/var/www/html/sites/default/modules"
      - "./default.conf:/etc/nginx/conf.d/default.conf"
      # - "./volumes/nginx-sample-website/conf.d/:/etc/nginx/conf.d"
      # - "./volumes/config/sample-website/config.js:/usr/share/nginx/html/config.js"
      - "./settings.php:/var/www/html/sites/default/settings.php"
      - "./composer.json:/var/www/html/composer.json"
      - "./composer.lock:/var/www/html/composer.lock"
      - "./vendor:/var/www/html/vendor"
      - "./php.ini:/etc/php/7.3/php.ini"
      - "./files:/var/www/html/sites/default/files"

      - "./www.conf:/etc/php/7.3/php-fpm.d/www.conf"
    environment:
      - DB_HOST=postgres
      - DB_NAME=banlist
      - DB_USER_NAME=postgres
      - DB_PASSWORD=postgres

      - __DEV__=true

      # - VIRTUAL_HOST=nodejs.banlist.info
      # - VIRTUAL_NETWORK=nginx-proxy
      # - VIRTUAL_PORT=80
      # - LETSENCRYPT_HOST=nodejs.banlist.info
      # - LETSENCRYPT_EMAIL=banlistmrs@gmail.com
    # networks:
    #   - default
    #   - specific-network-name

    # networks:
    #   - api-network

  postgres:
    image: postgres:11
    container_name: postgres
    environment:
      POSTGRES_DB: banlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
     - ./private/var/lib/postgresql:/var/lib/postgresql
    restart: always
    # networks:
    #   - api-network

  pgadmin:
    image: dpage/pgadmin4:4.18
    container_name: bigcard_pgadmin4
    ports:
      - 7778:80
    volumes:
      - ./pgadmin:/var/lib/pgadmin/storage
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres
      PGADMIN_DEFAULT_PASSWORD: postgres
    hostname: pgadmin4
    restart: always
    # networks:
    #   - api-network

# networks:
#   api-network:
#     name: project-name-network