# https://stackoverflow.com/questions/47901561/how-to-run-mongodb-and-mongo-express-with-docker-compose
version: '3.3'
services:
  nodejs:
    image: "nodejs"
    build: .
    # command: "node server.js"
    # ports:
    #   - "5000:5000"
    ports:
      - "8097:3000"
      - "8098:3001"
      - "9229:9229"
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "." 
    depends_on:
      - "mongo"
  mongo:
    image: "mongo"
    command: mongod --port 27099
    ports:
      - "27099:27099"
    volumes:
      - "./mongo/data:/data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=devroot
      - MONGO_INITDB_ROOT_PASSWORD=devroot
      - MONGO_INITDB_DATABASE=bl
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27099
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=devroot
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=devroot
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongo
    ports:
      - "8888:8081"