version: '2.4'
# version 2.x allows you to use depends_on with conditions that cause
# the node app to wait on mongo to respond to a healthy healthcheck before node is started
# v3.x doesn't have this feature yet, and is only needed if you want to use Swarm

services:
  nodejs_bl:
    container_name: nodejs_bl
    build:
      context: .
      args:
        - NODE_ENV=development
    # you can use legacy debug config or new inspect
    # NOTE: if nodemon isn't restarting on changes, you might be on Windows
    # which has trouble seeing file changes, so add -L to use legacy polling
    # https://github.com/remy/nodemon#application-isnt-restarting
    #command: ../node_modules/.bin/nodemon --debug=0.0.0.0:5858
    command: ../node_modules/.bin/nodemon --inspect=0.0.0.0:9229 ./bin/www
    ports:
      - "3000:3000"
      - "9229:9229"
      - "9230:9230"
    volumes:
      - .:/opt/node_app/app
      # bind-mounting these two files in will let you add packages during development without rebuilding
      # for example, to add bower to your app while developing, just install it inside the container
      # and then nodemon will restart. Your changes will last until you "docker-compose down" and will
      # be saved on host for next build
      # NOTE: this won't work on Docker Toolbox (virtualbox) which doesn't bind-mount single files
      # docker-compose exec node npm install --save bower
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.json:/opt/node_app/package-lock.json
      # this is a workaround to prevent host node_modules from accidently getting mounted in container
      # in case you want to use node/npm both outside container for test/lint etc. and also inside container
      # this will overwrite the default node_modules dir in container so it won't conflict with our
      # /opt/node_app/node_modules location. Thanks to PR from @brnluiz
      - notused:/opt/node_app/app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USERNAME=root
      - MONGO_PASSWORD=example
      - MONGO_HOSTNAME=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE_NAME=bl

      # cloud mongodb
      # - MONGO_HOSTNAME_ENV=143.198.223.146

      # cloud local กรณีเรารัน production เราจะรัน nodejs + mongo เครื่องเดียวกันดังนั้นเราจึง อ้าง mongo ใน docker-compose เดียวกันได้เลย
      - MONGO_HOSTNAME_ENV=mongo
      
      - MONGO_PORT_ENV=27017
      - MONGO_DATABASE_NAME_ENV=bl
      - MONGO_USERNAME_ENV=root
      - MONGO_PASSWORD_ENV=example

      - DRUPAL_API_ENV=http://128.199.217.244:8055
      - DRUPAL_AUTHORIZATION_ENV=c3dpZGVzd29kOjEyMzQ= # Authorization
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      disable: true
    networks:
      - nodejs-network

  mongo:
    # image: mongo:4
    image: "mongo"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=bl
    volumes:
      # this is an example of how to seed data in mongo containers. The Docker Hub mongo README
      # explains that any data dropped into the docker-entrypoint-initdb.d directory will be injected 
      # into mongo at startup. This is also a common pattern for other db solutions like mysql or psql
      - ./database:/docker-entrypoint-initdb.d
    # we need to check health here, so that docker-compose will wait for a healthy mongo before it starts node
    healthcheck:
      test: "[ `echo 'db.runCommand(\"ping\").ok' | mongo localhost/bl --quiet` ] && echo 0 || echo 1"
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
    networks:
      - nodejs-network
  
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_AUTH_USERNAME=root
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=example
      - ME_CONFIG_BASICAUTH_USERNAME=dev
      - ME_CONFIG_BASICAUTH_PASSWORD=dev
    depends_on:
      - mongo
    ports:
      - "8888:8081"
    networks:
      - nodejs-network

volumes:
  notused:
    
networks:
  nodejs-network:
    external:
      name: banlist-network
